### ISSUE TITLE
Welcome @daniele-russano!

### ISSUE THREAD

**Issue by igoramadas** [strautomator/contact#10]
Hi @daniele-russano,

Thanks for the support! Please send me your Strava ID here (or via [info@strautomator.com](mailto:info@strautomator.com)) so I can switch your Strautomator account to PRO manually. Unfortunately the system could not find your account based on username / first name / last name.

Best,

Igor

**Comment by ghost** [comment]
Hi Igor,

This is my Strava ID 123553264.

Thanks,
Daniele

Il giorno mer 9 ott 2024 alle ore 19:17 Igor Ramadas <
***@***.***> ha scritto:

**Comment by igoramadas** [comment]
Switched to PRO now. Enjoy the app!
