### ISSUE TITLE
Welcome @lbachan!

### ISSUE THREAD

**Issue by igoramadas** [strautomator/contact#11]
Hi @lbachan,

Thanks for the support! Please send me your Strava ID here (or via [info@strautomator.com](mailto:info@strautomator.com)) so I can switch your Strautomator account to PRO manually. Unfortunately the system could not find your account based on username / first name / last name.

Best,

Igor

**Comment by lbachan** [comment]
Hi Igor,

My Strava ID is https://www.strava.com/athletes/45307511.
Thanks alot for your help.

Regards,
Lackeshwar Bachan

**Comment by igoramadas** [comment]
Done, switched to PRO now :-)
