### ISSUE TITLE
Welcome @skuxy

### ISSUE THREAD

**Issue by igoramadas** [strautomator/contact#2]
Hi @skuxy!

Thanks for the support! If you setup the sponsorship to get a PRO account on Strautomator, please reply with your Strava ID (or send it to info@strautomator.com) so I can switch your account manually. Unfortunately the system could not find your account based on username / first name / last name.

**Comment by skuxy** [comment]
Ah, I guess that means I obfuscated my online accounts to an extent after all! And also explains strautomator status. My strava prodile ia https://strava.app.link/tEvbj9IYSHb

**Comment by igoramadas** [comment]
Done! Should be set to PRO in a few seconds.

**Comment by skuxy** [comment]
Much appreciated!
