### ISSUE TITLE
Welcome @niosus!

### ISSUE THREAD

**Issue by igoramadas** [strautomator/contact#6]
Hi @niosus,

Thanks for the support! Please send me your Strava ID here (or via [info@strautomator.com](mailto:info@strautomator.com)) so I can switch your Strautomator account to PRO manually. Unfortunately the system could not find your account based on username / first name / last name.

Best,

Igor

**Comment by niosus** [comment]
Hey @igoramadas, thanks for reaching out and for such an awesome tool!  
I sent an email with my Strava id as you suggested.
