### ISSUE TITLE
Welcome @AoifeSidhe!

### ISSUE THREAD

**Issue by igoramadas** [strautomator/contact#7]
Hi @AoifeSidhe,

Thanks for the support! Please send me your Strava ID here (or via [info@strautomator.com](mailto:info@strautomator.com)) so I can switch your Strautomator account to PRO manually. Unfortunately the system could not find your account based on username / first name / last name.

Best,

Igor

**Comment by AoifeSidhe** [comment]
Hello!
Thx for the great app!
My id is:
https://www.strava.com/athletes/121287622
