### ISSUE TITLE
Welcome @sgmess!

### ISSUE THREAD

**Issue by igoramadas** [strautomator/contact#9]
Hi @sgmess,

Thanks for the support! Please send me your Strava ID here (or via info@strautomator.com) so I can switch your Strautomator account to PRO manually. Unfortunately the system could not find your account based on username / first name / last name.

Best,

Igor

**Comment by sgmess** [comment]
Hi, Strava ID is 2147506.

Thanks

Steve

**Comment by igoramadas** [comment]
Switched to PRO now.
